### ISSUE TITLE
[Feature] chatRoom 관련

### ISSUE THREAD

**Issue by mike2ox** [42-Tomodachi/ft_transcendence#135]
### TODO
---
- 담당 : som-syom
- [x] 참여중인 채팅방 보기 누르면 해당 버튼은 다시 전체방 보기 로 바뀌도록 설정
- [x] 입장 눌렀을 때 비밀방인 경우 모달창 띄워지도록,
- [x] 비밀방이 아닌 경우 /chatroom/:id 로 라우팅 되도록 구현
- [x] 채팅방 만들기를 한 경우 response로 오는 roomId를 이용하여 /chatroom/:roomId 로 라우팅
- [x] 채팅방룸 안에서 친구목록 제거
- [x] 채팅방룸 내에서도 모달셋 추가
---
- 담당 : @mike2ox 
- [x] 시간세팅(@mike2ox)
- [x] 채팅방 내 타이틀 왼쪽에 뒤로가기 버튼 추가(@mike2ox)

_Originally posted by som-syom in https://github.com/42-Tomodachi/ft_transcendence/issues/132#issuecomment-1180347942_
